SET EXCLUSIVE ON
CLOSE DATABASES ALL
LOCAL LLTARGETCO, LLSOURCECO, LLTARGETPATH, LLSOURCEPATH
TEMP01 = SYS(2015)
TEMP02 = SYS(2015)

LLSOURCECO = 'I'
LLTARGETCO = 'Q'

LLSOURCEPATH = 'C:\Data\Comp_I\'
LLTARGETPATH = 'C:\Data\Comp_Q\'

LOCAL OTABLENAME
SELECT * FROM "C:\ProgramData\Pegasus\O3 Server VFP\DataDict\table.dbf" WHERE ALLTRIM(NAME) != 'jx_user' AND MODULEID != 'Y' AND NOT EMPTY(MODULEID) INTO CURSOR CTABLES
COPY TO ARRAY OTABLES FIELDS NAME
NROWCOUNT = ALEN(OTABLES, 1)
FOR NROW = 1 TO NROWCOUNT
	OTABLENAME = TRANSFORM(ALLTRIM(OTABLES[nRow]))
	IF OTABLENAME = 'jx_user' OR OTABLENAME = 'dmphasedet' OR OTABLENAME = 'seqeimph' OR OTABLENAME = 'seqeimpd' THEN
	ELSE
		USE  LLTARGETPATH + LLTARGETCO + '_' + OTABLENAME
		DELETE ALL
		PACK
		APPEND FROM LLSOURCEPATH + LLSOURCECO + '_' + OTABLENAME
	ENDIF
ENDFOR
USE  LLTARGETPATH + LLTARGETCO + '_ntran.dbf'
REPLACE ALL nt_srcco WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_ndetail.dbf'
REPLACE ALL nt_srcco WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_anoml.dbf'
REPLACE ALL ax_srcco WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_arhead.dbf'
REPLACE ALL ae_srcco WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_pnoml.dbf'
REPLACE ALL px_srcco WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_sparm.dbf'
REPLACE ALL sp_nlcoid WITH LLTARGETCO
USE  LLTARGETPATH + LLTARGETCO + '_pparm.dbf'
REPLACE ALL pp_nlcoid WITH LLTARGETCO
CLOSE DATABASES ALL
MESSAGEBOX("Complete",0,"Status")